sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  global:
language: node_js
node_js:
  - "8"
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  #- rm -rf docs
  - npm install
  - npm i https://github.com/meta-magic/d3-charts-tar/blob/master/amexio-chart-d3.tgz?raw=true
  - npm i https://github.com/meta-magic/amexio-ios/blob/v5.11/amexio-ng-extensions.tgz?raw=true
  #- ng build --prod
  - ng build
after_success: 
  - codecov
  - git clone https://github.com/meta-magic/amexio-ce-demo.git -b master
  - cd amexio-ce-demo/
  - rm -rf docs/*
  - cp -rf ../docs/* docs/
  - git add docs
  - git commit -m "[skip travis]  docs-updated"
  - git push  "https://deepali-arvind:${GITHUB_TOKEN}@github.com/meta-magic/amexio-ce-demo.git" HEAD:master
cache:
  yarn: true
