sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
     - google-chrome
    packages:
      - google-chrome-stable

env:
  global:
language: node_js
node_js:
  - "8"
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- npm install --global gulp --save
script: 
  - npm install
  - npm i https://github.com/meta-magic/d3-charts-tar/blob/master/amexio-chart-d3.tgz?raw=true
  - npm i https://github.com/meta-magic/amexio-ios/blob/v5.12/amexio-ng-extensions.tgz?raw=true
  - ng build
after_success: 
  - codecov
  - git clone https://github.com/meta-magic/amexio-api-website-test.git
  - rm -rf amexio-api-website-test/demo/ce-demo/*
  - cp -rf docs/* amexio-api-website-test/demo/ce-demo/
  - cd amexio-api-website-test/
  - git add demo/ce-demo/
  - git commit -m "DATE"
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push "https://deepali-arvind:${TOKEN}@github.com/${REPO}.git" HEAD:master; fi
cache:
  yarn: true
